  // This file is generated by scripts/gen_callconv_tests.rb -- do not edit
  #include <stdint.h>

  #define NULL ((void*) 0)

  // [limitation--no-relocatable] due to a known limitation, we can't process
  // relocatable executables (we can't run relocations at all).
  // adding main() allows us to compile this to a 'full' executable rather than a .o
  int main() {}


    uint8_t __attribute__ ((noinline)) func000_in(uint8_t arg0) {
      return arg0;
    }

    uint8_t func000_out() {
      
        uint8_t example_value0 = 211;
      
      return func000_in(
        example_value0
      );
    }

    uint16_t __attribute__ ((noinline)) func001_in(uint16_t arg0) {
      return arg0;
    }

    uint16_t func001_out() {
      
        uint16_t example_value0 = 31187;
      
      return func001_in(
        example_value0
      );
    }

    uint32_t __attribute__ ((noinline)) func002_in(uint32_t arg0) {
      return arg0;
    }

    uint32_t func002_out() {
      
        uint32_t example_value0 = 3457513939;
      
      return func002_in(
        example_value0
      );
    }

    uint64_t __attribute__ ((noinline)) func003_in(uint64_t arg0) {
      return arg0;
    }

    uint64_t func003_out() {
      
        uint64_t example_value0 = 329875028435;
      
      return func003_in(
        example_value0
      );
    }

    void *__attribute__ ((noinline)) func004_in(void *arg0) {
      return arg0;
    }

    void *func004_out() {
      
        void *example_value0 = NULL;
      
      return func004_in(
        example_value0
      );
    }

    float __attribute__ ((noinline)) func005_in(float arg0) {
      return arg0;
    }

    float func005_out() {
      
        float example_value0 = 123.456f;
      
      return func005_in(
        example_value0
      );
    }

    double __attribute__ ((noinline)) func006_in(double arg0) {
      return arg0;
    }

    double func006_out() {
      
        double example_value0 = 987.321000;
      
      return func006_in(
        example_value0
      );
    }



struct small {
  void *member0;
  float member1;
  uint8_t member2;
};
    void *__attribute__ ((noinline)) func007_in(struct small arg0) {
      return arg0.member0;
    }

    void *func007_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func007_in(
        example_value0
      );
    }
    float __attribute__ ((noinline)) func008_in(struct small arg0) {
      return arg0.member1;
    }

    float func008_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func008_in(
        example_value0
      );
    }
    uint8_t __attribute__ ((noinline)) func009_in(struct small arg0) {
      return arg0.member2;
    }

    uint8_t func009_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func009_in(
        example_value0
      );
    }


struct small_xmms {
  float member0;
  double member1;
};
    float __attribute__ ((noinline)) func010_in(struct small_xmms arg0) {
      return arg0.member0;
    }

    float func010_out() {
      
        struct small_xmms example_value0 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func010_in(
        example_value0
      );
    }
    double __attribute__ ((noinline)) func011_in(struct small_xmms arg0) {
      return arg0.member1;
    }

    double func011_out() {
      
        struct small_xmms example_value0 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func011_in(
        example_value0
      );
    }






struct big {
  float member0;
  double member1;
  void *member2;
  uint8_t member3;
  uint8_t member4[3];
};
    float __attribute__ ((noinline)) func012_in(struct big arg0) {
      return arg0.member0;
    }

    float func012_out() {
      
        struct big example_value0 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func012_in(
        example_value0
      );
    }
    double __attribute__ ((noinline)) func013_in(struct big arg0) {
      return arg0.member1;
    }

    double func013_out() {
      
        struct big example_value0 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func013_in(
        example_value0
      );
    }
    void *__attribute__ ((noinline)) func014_in(struct big arg0) {
      return arg0.member2;
    }

    void *func014_out() {
      
        struct big example_value0 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func014_in(
        example_value0
      );
    }
    uint8_t __attribute__ ((noinline)) func015_in(struct big arg0) {
      return arg0.member3;
    }

    uint8_t func015_out() {
      
        struct big example_value0 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func015_in(
        example_value0
      );
    }
    uint8_t __attribute__ ((noinline)) func016_in(struct big arg0) {
      return arg0.member4[0];
    }

    uint8_t func016_out() {
      
        struct big example_value0 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func016_in(
        example_value0
      );
    }
    uint8_t __attribute__ ((noinline)) func017_in(struct big arg0) {
      return arg0.member4[1];
    }

    uint8_t func017_out() {
      
        struct big example_value0 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func017_in(
        example_value0
      );
    }
    uint8_t __attribute__ ((noinline)) func018_in(struct big arg0) {
      return arg0.member4[2];
    }

    uint8_t func018_out() {
      
        struct big example_value0 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func018_in(
        example_value0
      );
    }
    uint8_t __attribute__ ((noinline)) func019_in(struct small arg0, uint8_t arg1) {
      return arg1;
    }

    uint8_t func019_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint8_t example_value1 = 211;
      
      return func019_in(
        example_value0, example_value1
      );
    }
    uint16_t __attribute__ ((noinline)) func020_in(struct small arg0, uint16_t arg1) {
      return arg1;
    }

    uint16_t func020_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint16_t example_value1 = 31187;
      
      return func020_in(
        example_value0, example_value1
      );
    }
    uint32_t __attribute__ ((noinline)) func021_in(struct small arg0, uint32_t arg1) {
      return arg1;
    }

    uint32_t func021_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint32_t example_value1 = 3457513939;
      
      return func021_in(
        example_value0, example_value1
      );
    }
    uint64_t __attribute__ ((noinline)) func022_in(struct small arg0, uint64_t arg1) {
      return arg1;
    }

    uint64_t func022_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint64_t example_value1 = 329875028435;
      
      return func022_in(
        example_value0, example_value1
      );
    }
    void *__attribute__ ((noinline)) func023_in(struct small arg0, void *arg1) {
      return arg1;
    }

    void *func023_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        void *example_value1 = NULL;
      
      return func023_in(
        example_value0, example_value1
      );
    }
    float __attribute__ ((noinline)) func024_in(struct small arg0, float arg1) {
      return arg1;
    }

    float func024_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        float example_value1 = 123.456f;
      
      return func024_in(
        example_value0, example_value1
      );
    }
    double __attribute__ ((noinline)) func025_in(struct small arg0, double arg1) {
      return arg1;
    }

    double func025_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        double example_value1 = 987.321000;
      
      return func025_in(
        example_value0, example_value1
      );
    }
    void *__attribute__ ((noinline)) func026_in(struct small arg0, struct small arg1) {
      return arg1.member0;
    }

    void *func026_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func026_in(
        example_value0, example_value1
      );
    }
    float __attribute__ ((noinline)) func027_in(struct small arg0, struct small arg1) {
      return arg1.member1;
    }

    float func027_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func027_in(
        example_value0, example_value1
      );
    }
    uint8_t __attribute__ ((noinline)) func028_in(struct small arg0, struct small arg1) {
      return arg1.member2;
    }

    uint8_t func028_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func028_in(
        example_value0, example_value1
      );
    }
    float __attribute__ ((noinline)) func029_in(struct small arg0, struct small_xmms arg1) {
      return arg1.member0;
    }

    float func029_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value1 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func029_in(
        example_value0, example_value1
      );
    }
    double __attribute__ ((noinline)) func030_in(struct small arg0, struct small_xmms arg1) {
      return arg1.member1;
    }

    double func030_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value1 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func030_in(
        example_value0, example_value1
      );
    }
    float __attribute__ ((noinline)) func031_in(struct small arg0, struct big arg1) {
      return arg1.member0;
    }

    float func031_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value1 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func031_in(
        example_value0, example_value1
      );
    }
    double __attribute__ ((noinline)) func032_in(struct small arg0, struct big arg1) {
      return arg1.member1;
    }

    double func032_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value1 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func032_in(
        example_value0, example_value1
      );
    }
    void *__attribute__ ((noinline)) func033_in(struct small arg0, struct big arg1) {
      return arg1.member2;
    }

    void *func033_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value1 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func033_in(
        example_value0, example_value1
      );
    }
    uint8_t __attribute__ ((noinline)) func034_in(struct small arg0, struct big arg1) {
      return arg1.member3;
    }

    uint8_t func034_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value1 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func034_in(
        example_value0, example_value1
      );
    }
    uint8_t __attribute__ ((noinline)) func035_in(struct small arg0, struct big arg1) {
      return arg1.member4[0];
    }

    uint8_t func035_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value1 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func035_in(
        example_value0, example_value1
      );
    }
    uint8_t __attribute__ ((noinline)) func036_in(struct small arg0, struct big arg1) {
      return arg1.member4[1];
    }

    uint8_t func036_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value1 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func036_in(
        example_value0, example_value1
      );
    }
    uint8_t __attribute__ ((noinline)) func037_in(struct small arg0, struct big arg1) {
      return arg1.member4[2];
    }

    uint8_t func037_out() {
      
        struct small example_value0 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value1 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func037_in(
        example_value0, example_value1
      );
    }

    uint8_t __attribute__ ((noinline)) func038_in(void *arg0, struct small arg1, uint8_t arg2) {
      return arg2;
    }

    uint8_t func038_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint8_t example_value2 = 211;
      
      return func038_in(
        example_value0, example_value1, example_value2
      );
    }
    uint16_t __attribute__ ((noinline)) func039_in(void *arg0, struct small arg1, uint16_t arg2) {
      return arg2;
    }

    uint16_t func039_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint16_t example_value2 = 31187;
      
      return func039_in(
        example_value0, example_value1, example_value2
      );
    }
    uint32_t __attribute__ ((noinline)) func040_in(void *arg0, struct small arg1, uint32_t arg2) {
      return arg2;
    }

    uint32_t func040_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint32_t example_value2 = 3457513939;
      
      return func040_in(
        example_value0, example_value1, example_value2
      );
    }
    uint64_t __attribute__ ((noinline)) func041_in(void *arg0, struct small arg1, uint64_t arg2) {
      return arg2;
    }

    uint64_t func041_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint64_t example_value2 = 329875028435;
      
      return func041_in(
        example_value0, example_value1, example_value2
      );
    }
    void *__attribute__ ((noinline)) func042_in(void *arg0, struct small arg1, void *arg2) {
      return arg2;
    }

    void *func042_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        void *example_value2 = NULL;
      
      return func042_in(
        example_value0, example_value1, example_value2
      );
    }
    float __attribute__ ((noinline)) func043_in(void *arg0, struct small arg1, float arg2) {
      return arg2;
    }

    float func043_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        float example_value2 = 123.456f;
      
      return func043_in(
        example_value0, example_value1, example_value2
      );
    }
    double __attribute__ ((noinline)) func044_in(void *arg0, struct small arg1, double arg2) {
      return arg2;
    }

    double func044_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        double example_value2 = 987.321000;
      
      return func044_in(
        example_value0, example_value1, example_value2
      );
    }
    void *__attribute__ ((noinline)) func045_in(void *arg0, struct small arg1, struct small arg2) {
      return arg2.member0;
    }

    void *func045_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func045_in(
        example_value0, example_value1, example_value2
      );
    }
    float __attribute__ ((noinline)) func046_in(void *arg0, struct small arg1, struct small arg2) {
      return arg2.member1;
    }

    float func046_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func046_in(
        example_value0, example_value1, example_value2
      );
    }
    uint8_t __attribute__ ((noinline)) func047_in(void *arg0, struct small arg1, struct small arg2) {
      return arg2.member2;
    }

    uint8_t func047_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func047_in(
        example_value0, example_value1, example_value2
      );
    }
    float __attribute__ ((noinline)) func048_in(void *arg0, struct small arg1, struct small_xmms arg2) {
      return arg2.member0;
    }

    float func048_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value2 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func048_in(
        example_value0, example_value1, example_value2
      );
    }
    double __attribute__ ((noinline)) func049_in(void *arg0, struct small arg1, struct small_xmms arg2) {
      return arg2.member1;
    }

    double func049_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value2 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func049_in(
        example_value0, example_value1, example_value2
      );
    }
    float __attribute__ ((noinline)) func050_in(void *arg0, struct small arg1, struct big arg2) {
      return arg2.member0;
    }

    float func050_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value2 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func050_in(
        example_value0, example_value1, example_value2
      );
    }
    double __attribute__ ((noinline)) func051_in(void *arg0, struct small arg1, struct big arg2) {
      return arg2.member1;
    }

    double func051_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value2 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func051_in(
        example_value0, example_value1, example_value2
      );
    }
    void *__attribute__ ((noinline)) func052_in(void *arg0, struct small arg1, struct big arg2) {
      return arg2.member2;
    }

    void *func052_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value2 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func052_in(
        example_value0, example_value1, example_value2
      );
    }
    uint8_t __attribute__ ((noinline)) func053_in(void *arg0, struct small arg1, struct big arg2) {
      return arg2.member3;
    }

    uint8_t func053_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value2 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func053_in(
        example_value0, example_value1, example_value2
      );
    }
    uint8_t __attribute__ ((noinline)) func054_in(void *arg0, struct small arg1, struct big arg2) {
      return arg2.member4[0];
    }

    uint8_t func054_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value2 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func054_in(
        example_value0, example_value1, example_value2
      );
    }
    uint8_t __attribute__ ((noinline)) func055_in(void *arg0, struct small arg1, struct big arg2) {
      return arg2.member4[1];
    }

    uint8_t func055_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value2 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func055_in(
        example_value0, example_value1, example_value2
      );
    }
    uint8_t __attribute__ ((noinline)) func056_in(void *arg0, struct small arg1, struct big arg2) {
      return arg2.member4[2];
    }

    uint8_t func056_out() {
      
        void *example_value0 = NULL;
      
        struct small example_value1 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value2 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func056_in(
        example_value0, example_value1, example_value2
      );
    }
    uint8_t __attribute__ ((noinline)) func057_in(void *arg0, void *arg1, struct small arg2, uint8_t arg3) {
      return arg3;
    }

    uint8_t func057_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint8_t example_value3 = 211;
      
      return func057_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    uint16_t __attribute__ ((noinline)) func058_in(void *arg0, void *arg1, struct small arg2, uint16_t arg3) {
      return arg3;
    }

    uint16_t func058_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint16_t example_value3 = 31187;
      
      return func058_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    uint32_t __attribute__ ((noinline)) func059_in(void *arg0, void *arg1, struct small arg2, uint32_t arg3) {
      return arg3;
    }

    uint32_t func059_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint32_t example_value3 = 3457513939;
      
      return func059_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    uint64_t __attribute__ ((noinline)) func060_in(void *arg0, void *arg1, struct small arg2, uint64_t arg3) {
      return arg3;
    }

    uint64_t func060_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint64_t example_value3 = 329875028435;
      
      return func060_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    void *__attribute__ ((noinline)) func061_in(void *arg0, void *arg1, struct small arg2, void *arg3) {
      return arg3;
    }

    void *func061_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        void *example_value3 = NULL;
      
      return func061_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    float __attribute__ ((noinline)) func062_in(void *arg0, void *arg1, struct small arg2, float arg3) {
      return arg3;
    }

    float func062_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        float example_value3 = 123.456f;
      
      return func062_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    double __attribute__ ((noinline)) func063_in(void *arg0, void *arg1, struct small arg2, double arg3) {
      return arg3;
    }

    double func063_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        double example_value3 = 987.321000;
      
      return func063_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    void *__attribute__ ((noinline)) func064_in(void *arg0, void *arg1, struct small arg2, struct small arg3) {
      return arg3.member0;
    }

    void *func064_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func064_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    float __attribute__ ((noinline)) func065_in(void *arg0, void *arg1, struct small arg2, struct small arg3) {
      return arg3.member1;
    }

    float func065_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func065_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    uint8_t __attribute__ ((noinline)) func066_in(void *arg0, void *arg1, struct small arg2, struct small arg3) {
      return arg3.member2;
    }

    uint8_t func066_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func066_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    float __attribute__ ((noinline)) func067_in(void *arg0, void *arg1, struct small arg2, struct small_xmms arg3) {
      return arg3.member0;
    }

    float func067_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value3 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func067_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    double __attribute__ ((noinline)) func068_in(void *arg0, void *arg1, struct small arg2, struct small_xmms arg3) {
      return arg3.member1;
    }

    double func068_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value3 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func068_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    float __attribute__ ((noinline)) func069_in(void *arg0, void *arg1, struct small arg2, struct big arg3) {
      return arg3.member0;
    }

    float func069_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value3 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func069_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    double __attribute__ ((noinline)) func070_in(void *arg0, void *arg1, struct small arg2, struct big arg3) {
      return arg3.member1;
    }

    double func070_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value3 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func070_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    void *__attribute__ ((noinline)) func071_in(void *arg0, void *arg1, struct small arg2, struct big arg3) {
      return arg3.member2;
    }

    void *func071_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value3 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func071_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    uint8_t __attribute__ ((noinline)) func072_in(void *arg0, void *arg1, struct small arg2, struct big arg3) {
      return arg3.member3;
    }

    uint8_t func072_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value3 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func072_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    uint8_t __attribute__ ((noinline)) func073_in(void *arg0, void *arg1, struct small arg2, struct big arg3) {
      return arg3.member4[0];
    }

    uint8_t func073_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value3 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func073_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    uint8_t __attribute__ ((noinline)) func074_in(void *arg0, void *arg1, struct small arg2, struct big arg3) {
      return arg3.member4[1];
    }

    uint8_t func074_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value3 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func074_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    uint8_t __attribute__ ((noinline)) func075_in(void *arg0, void *arg1, struct small arg2, struct big arg3) {
      return arg3.member4[2];
    }

    uint8_t func075_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        struct small example_value2 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value3 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func075_in(
        example_value0, example_value1, example_value2, example_value3
      );
    }
    uint8_t __attribute__ ((noinline)) func076_in(void *arg0, void *arg1, void *arg2, struct small arg3, uint8_t arg4) {
      return arg4;
    }

    uint8_t func076_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint8_t example_value4 = 211;
      
      return func076_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    uint16_t __attribute__ ((noinline)) func077_in(void *arg0, void *arg1, void *arg2, struct small arg3, uint16_t arg4) {
      return arg4;
    }

    uint16_t func077_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint16_t example_value4 = 31187;
      
      return func077_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    uint32_t __attribute__ ((noinline)) func078_in(void *arg0, void *arg1, void *arg2, struct small arg3, uint32_t arg4) {
      return arg4;
    }

    uint32_t func078_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint32_t example_value4 = 3457513939;
      
      return func078_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    uint64_t __attribute__ ((noinline)) func079_in(void *arg0, void *arg1, void *arg2, struct small arg3, uint64_t arg4) {
      return arg4;
    }

    uint64_t func079_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint64_t example_value4 = 329875028435;
      
      return func079_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    void *__attribute__ ((noinline)) func080_in(void *arg0, void *arg1, void *arg2, struct small arg3, void *arg4) {
      return arg4;
    }

    void *func080_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        void *example_value4 = NULL;
      
      return func080_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    float __attribute__ ((noinline)) func081_in(void *arg0, void *arg1, void *arg2, struct small arg3, float arg4) {
      return arg4;
    }

    float func081_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        float example_value4 = 123.456f;
      
      return func081_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    double __attribute__ ((noinline)) func082_in(void *arg0, void *arg1, void *arg2, struct small arg3, double arg4) {
      return arg4;
    }

    double func082_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        double example_value4 = 987.321000;
      
      return func082_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    void *__attribute__ ((noinline)) func083_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct small arg4) {
      return arg4.member0;
    }

    void *func083_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func083_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    float __attribute__ ((noinline)) func084_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct small arg4) {
      return arg4.member1;
    }

    float func084_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func084_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    uint8_t __attribute__ ((noinline)) func085_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct small arg4) {
      return arg4.member2;
    }

    uint8_t func085_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func085_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    float __attribute__ ((noinline)) func086_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct small_xmms arg4) {
      return arg4.member0;
    }

    float func086_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value4 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func086_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    double __attribute__ ((noinline)) func087_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct small_xmms arg4) {
      return arg4.member1;
    }

    double func087_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value4 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func087_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    float __attribute__ ((noinline)) func088_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct big arg4) {
      return arg4.member0;
    }

    float func088_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value4 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func088_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    double __attribute__ ((noinline)) func089_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct big arg4) {
      return arg4.member1;
    }

    double func089_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value4 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func089_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    void *__attribute__ ((noinline)) func090_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct big arg4) {
      return arg4.member2;
    }

    void *func090_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value4 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func090_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    uint8_t __attribute__ ((noinline)) func091_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct big arg4) {
      return arg4.member3;
    }

    uint8_t func091_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value4 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func091_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    uint8_t __attribute__ ((noinline)) func092_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct big arg4) {
      return arg4.member4[0];
    }

    uint8_t func092_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value4 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func092_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    uint8_t __attribute__ ((noinline)) func093_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct big arg4) {
      return arg4.member4[1];
    }

    uint8_t func093_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value4 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func093_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    uint8_t __attribute__ ((noinline)) func094_in(void *arg0, void *arg1, void *arg2, struct small arg3, struct big arg4) {
      return arg4.member4[2];
    }

    uint8_t func094_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        struct small example_value3 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value4 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func094_in(
        example_value0, example_value1, example_value2, example_value3, example_value4
      );
    }
    uint8_t __attribute__ ((noinline)) func095_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, uint8_t arg5) {
      return arg5;
    }

    uint8_t func095_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint8_t example_value5 = 211;
      
      return func095_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    uint16_t __attribute__ ((noinline)) func096_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, uint16_t arg5) {
      return arg5;
    }

    uint16_t func096_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint16_t example_value5 = 31187;
      
      return func096_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    uint32_t __attribute__ ((noinline)) func097_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, uint32_t arg5) {
      return arg5;
    }

    uint32_t func097_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint32_t example_value5 = 3457513939;
      
      return func097_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    uint64_t __attribute__ ((noinline)) func098_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, uint64_t arg5) {
      return arg5;
    }

    uint64_t func098_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint64_t example_value5 = 329875028435;
      
      return func098_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    void *__attribute__ ((noinline)) func099_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, void *arg5) {
      return arg5;
    }

    void *func099_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        void *example_value5 = NULL;
      
      return func099_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    float __attribute__ ((noinline)) func100_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, float arg5) {
      return arg5;
    }

    float func100_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        float example_value5 = 123.456f;
      
      return func100_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    double __attribute__ ((noinline)) func101_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, double arg5) {
      return arg5;
    }

    double func101_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        double example_value5 = 987.321000;
      
      return func101_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    void *__attribute__ ((noinline)) func102_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct small arg5) {
      return arg5.member0;
    }

    void *func102_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func102_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    float __attribute__ ((noinline)) func103_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct small arg5) {
      return arg5.member1;
    }

    float func103_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func103_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    uint8_t __attribute__ ((noinline)) func104_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct small arg5) {
      return arg5.member2;
    }

    uint8_t func104_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func104_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    float __attribute__ ((noinline)) func105_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct small_xmms arg5) {
      return arg5.member0;
    }

    float func105_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value5 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func105_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    double __attribute__ ((noinline)) func106_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct small_xmms arg5) {
      return arg5.member1;
    }

    double func106_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value5 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func106_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    float __attribute__ ((noinline)) func107_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct big arg5) {
      return arg5.member0;
    }

    float func107_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value5 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func107_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    double __attribute__ ((noinline)) func108_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct big arg5) {
      return arg5.member1;
    }

    double func108_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value5 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func108_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    void *__attribute__ ((noinline)) func109_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct big arg5) {
      return arg5.member2;
    }

    void *func109_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value5 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func109_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    uint8_t __attribute__ ((noinline)) func110_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct big arg5) {
      return arg5.member3;
    }

    uint8_t func110_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value5 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func110_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    uint8_t __attribute__ ((noinline)) func111_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct big arg5) {
      return arg5.member4[0];
    }

    uint8_t func111_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value5 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func111_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    uint8_t __attribute__ ((noinline)) func112_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct big arg5) {
      return arg5.member4[1];
    }

    uint8_t func112_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value5 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func112_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    uint8_t __attribute__ ((noinline)) func113_in(void *arg0, void *arg1, void *arg2, void *arg3, struct small arg4, struct big arg5) {
      return arg5.member4[2];
    }

    uint8_t func113_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        struct small example_value4 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value5 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func113_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5
      );
    }
    uint8_t __attribute__ ((noinline)) func114_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, uint8_t arg6) {
      return arg6;
    }

    uint8_t func114_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint8_t example_value6 = 211;
      
      return func114_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    uint16_t __attribute__ ((noinline)) func115_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, uint16_t arg6) {
      return arg6;
    }

    uint16_t func115_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint16_t example_value6 = 31187;
      
      return func115_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    uint32_t __attribute__ ((noinline)) func116_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, uint32_t arg6) {
      return arg6;
    }

    uint32_t func116_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint32_t example_value6 = 3457513939;
      
      return func116_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    uint64_t __attribute__ ((noinline)) func117_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, uint64_t arg6) {
      return arg6;
    }

    uint64_t func117_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint64_t example_value6 = 329875028435;
      
      return func117_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    void *__attribute__ ((noinline)) func118_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, void *arg6) {
      return arg6;
    }

    void *func118_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        void *example_value6 = NULL;
      
      return func118_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    float __attribute__ ((noinline)) func119_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, float arg6) {
      return arg6;
    }

    float func119_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        float example_value6 = 123.456f;
      
      return func119_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    double __attribute__ ((noinline)) func120_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, double arg6) {
      return arg6;
    }

    double func120_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        double example_value6 = 987.321000;
      
      return func120_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    void *__attribute__ ((noinline)) func121_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct small arg6) {
      return arg6.member0;
    }

    void *func121_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func121_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    float __attribute__ ((noinline)) func122_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct small arg6) {
      return arg6.member1;
    }

    float func122_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func122_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    uint8_t __attribute__ ((noinline)) func123_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct small arg6) {
      return arg6.member2;
    }

    uint8_t func123_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func123_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    float __attribute__ ((noinline)) func124_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct small_xmms arg6) {
      return arg6.member0;
    }

    float func124_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value6 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func124_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    double __attribute__ ((noinline)) func125_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct small_xmms arg6) {
      return arg6.member1;
    }

    double func125_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value6 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func125_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    float __attribute__ ((noinline)) func126_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct big arg6) {
      return arg6.member0;
    }

    float func126_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value6 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func126_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    double __attribute__ ((noinline)) func127_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct big arg6) {
      return arg6.member1;
    }

    double func127_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value6 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func127_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    void *__attribute__ ((noinline)) func128_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct big arg6) {
      return arg6.member2;
    }

    void *func128_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value6 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func128_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    uint8_t __attribute__ ((noinline)) func129_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct big arg6) {
      return arg6.member3;
    }

    uint8_t func129_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value6 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func129_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    uint8_t __attribute__ ((noinline)) func130_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct big arg6) {
      return arg6.member4[0];
    }

    uint8_t func130_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value6 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func130_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    uint8_t __attribute__ ((noinline)) func131_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct big arg6) {
      return arg6.member4[1];
    }

    uint8_t func131_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value6 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func131_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    uint8_t __attribute__ ((noinline)) func132_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, struct small arg5, struct big arg6) {
      return arg6.member4[2];
    }

    uint8_t func132_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        struct small example_value5 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value6 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func132_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6
      );
    }
    uint8_t __attribute__ ((noinline)) func133_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, uint8_t arg7) {
      return arg7;
    }

    uint8_t func133_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint8_t example_value7 = 211;
      
      return func133_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    uint16_t __attribute__ ((noinline)) func134_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, uint16_t arg7) {
      return arg7;
    }

    uint16_t func134_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint16_t example_value7 = 31187;
      
      return func134_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    uint32_t __attribute__ ((noinline)) func135_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, uint32_t arg7) {
      return arg7;
    }

    uint32_t func135_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint32_t example_value7 = 3457513939;
      
      return func135_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    uint64_t __attribute__ ((noinline)) func136_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, uint64_t arg7) {
      return arg7;
    }

    uint64_t func136_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        uint64_t example_value7 = 329875028435;
      
      return func136_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    void *__attribute__ ((noinline)) func137_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, void *arg7) {
      return arg7;
    }

    void *func137_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        void *example_value7 = NULL;
      
      return func137_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    float __attribute__ ((noinline)) func138_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, float arg7) {
      return arg7;
    }

    float func138_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        float example_value7 = 123.456f;
      
      return func138_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    double __attribute__ ((noinline)) func139_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, double arg7) {
      return arg7;
    }

    double func139_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        double example_value7 = 987.321000;
      
      return func139_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    void *__attribute__ ((noinline)) func140_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct small arg7) {
      return arg7.member0;
    }

    void *func140_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value7 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func140_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    float __attribute__ ((noinline)) func141_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct small arg7) {
      return arg7.member1;
    }

    float func141_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value7 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func141_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    uint8_t __attribute__ ((noinline)) func142_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct small arg7) {
      return arg7.member2;
    }

    uint8_t func142_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small example_value7 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
      return func142_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    float __attribute__ ((noinline)) func143_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct small_xmms arg7) {
      return arg7.member0;
    }

    float func143_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value7 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func143_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    double __attribute__ ((noinline)) func144_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct small_xmms arg7) {
      return arg7.member1;
    }

    double func144_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct small_xmms example_value7 = (struct small_xmms){ .member0 = 123.456f, .member1 = 987.321000 };
      
      return func144_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    float __attribute__ ((noinline)) func145_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct big arg7) {
      return arg7.member0;
    }

    float func145_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value7 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func145_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    double __attribute__ ((noinline)) func146_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct big arg7) {
      return arg7.member1;
    }

    double func146_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value7 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func146_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    void *__attribute__ ((noinline)) func147_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct big arg7) {
      return arg7.member2;
    }

    void *func147_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value7 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func147_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    uint8_t __attribute__ ((noinline)) func148_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct big arg7) {
      return arg7.member3;
    }

    uint8_t func148_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value7 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func148_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    uint8_t __attribute__ ((noinline)) func149_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct big arg7) {
      return arg7.member4[0];
    }

    uint8_t func149_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value7 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func149_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    uint8_t __attribute__ ((noinline)) func150_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct big arg7) {
      return arg7.member4[1];
    }

    uint8_t func150_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value7 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func150_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
    uint8_t __attribute__ ((noinline)) func151_in(void *arg0, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, struct small arg6, struct big arg7) {
      return arg7.member4[2];
    }

    uint8_t func151_out() {
      
        void *example_value0 = NULL;
      
        void *example_value1 = NULL;
      
        void *example_value2 = NULL;
      
        void *example_value3 = NULL;
      
        void *example_value4 = NULL;
      
        void *example_value5 = NULL;
      
        struct small example_value6 = (struct small){ .member0 = NULL, .member1 = 123.456f, .member2 = 211 };
      
        struct big example_value7 = (struct big){ .member0 = 123.456f, .member1 = 987.321000, .member2 = NULL, .member3 = 211, .member4 = { 211, 211, 211 } };
      
      return func151_in(
        example_value0, example_value1, example_value2, example_value3, example_value4, example_value5, example_value6, example_value7
      );
    }
